### ISSUE TITLE
Could you give information?

### ISSUE THREAD

**Issue by mehmetserdarcelik** [hananabilabd/EMG-Classification-Visualization-using-MYO-ArmBand-Raspberry-Pi#1]
Dear Hanna,

First of all thank you for this work to help us! I have a problem with that library and I want to ask you. I'm new at Rasp Pi and not good at Linux programming. When I update my Rasp Pi I see there are two versions of Python. The first one is 2.7 and the other is 3.7. Therefore installing your library and requirements there are two options. When I run the example code on consol with "sudo python" there is not any error but I can not see the data or any graphs. But If I run it on IDE there are modules errors. So I want to ask have you use this code on updated Rasp Pi OS or on Python 3.7? And have you any ideas about these conflicts error?

**Comment by hananabilabd** [comment]
Hello 
In fact it was a long time ago since I did this project, I would say the most difficult part to put that project was installing Keras on RasberryPi, there was a blog that helped me doing this.
please send at hananabilabd@gmail.com if any further inquires are needed.
